<?php

namespace Coipeault\CN\MegapolisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends EntityRepository {
    
}
